// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC88fMiRjWUnmLBj20R9YV3gJPGSDMh6VA',
    appId: '1:717650442763:web:2aaa4b7b3754cb7f0c250e',
    messagingSenderId: '717650442763',
    projectId: 'kubi-test-f572a',
    authDomain: 'kubi-test-f572a.firebaseapp.com',
    storageBucket: 'kubi-test-f572a.firebasestorage.app',
    measurementId: 'G-MV0NE7YMW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmwOyK0z_vXaGBV-KvrWGd-k5z3q55CDY',
    appId: '1:717650442763:android:48f9ad538be620440c250e',
    messagingSenderId: '717650442763',
    projectId: 'kubi-test-f572a',
    storageBucket: 'kubi-test-f572a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqOYqi723fqKNLvKKhSIBpi3aHtlGlhs',
    appId: '1:717650442763:ios:14dcfc422ea973bd0c250e',
    messagingSenderId: '717650442763',
    projectId: 'kubi-test-f572a',
    storageBucket: 'kubi-test-f572a.firebasestorage.app',
    iosBundleId: 'com.example.personalTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqOYqi723fqKNLvKKhSIBpi3aHtlGlhs',
    appId: '1:717650442763:ios:14dcfc422ea973bd0c250e',
    messagingSenderId: '717650442763',
    projectId: 'kubi-test-f572a',
    storageBucket: 'kubi-test-f572a.firebasestorage.app',
    iosBundleId: 'com.example.personalTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC88fMiRjWUnmLBj20R9YV3gJPGSDMh6VA',
    appId: '1:717650442763:web:d796b1d729a3e3a70c250e',
    messagingSenderId: '717650442763',
    projectId: 'kubi-test-f572a',
    authDomain: 'kubi-test-f572a.firebaseapp.com',
    storageBucket: 'kubi-test-f572a.firebasestorage.app',
    measurementId: 'G-YH815VGDXX',
  );
}
